// Autogenerated from Pigeon (v11.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "GeneratedQqOpenSdkPluginApi.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

@implementation QQSceneTypeBox
- (instancetype)initWithValue:(QQSceneType)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation QQShareRetCodeBox
- (instancetype)initWithValue:(QQShareRetCode)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface QQShareBaseModel ()
+ (QQShareBaseModel *)fromList:(NSArray *)list;
+ (nullable QQShareBaseModel *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface QQSdkOnResp ()
+ (QQSdkOnResp *)fromList:(NSArray *)list;
+ (nullable QQSdkOnResp *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface QQShareWebPage ()
+ (QQShareWebPage *)fromList:(NSArray *)list;
+ (nullable QQShareWebPage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface QQShareImage ()
+ (QQShareImage *)fromList:(NSArray *)list;
+ (nullable QQShareImage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation QQShareBaseModel
+ (instancetype)makeWithTitle:(NSString *)title
    content:(NSString *)content
    scene:(QQSceneType)scene {
  QQShareBaseModel* pigeonResult = [[QQShareBaseModel alloc] init];
  pigeonResult.title = title;
  pigeonResult.content = content;
  pigeonResult.scene = scene;
  return pigeonResult;
}
+ (QQShareBaseModel *)fromList:(NSArray *)list {
  QQShareBaseModel *pigeonResult = [[QQShareBaseModel alloc] init];
  pigeonResult.title = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.title != nil, @"");
  pigeonResult.content = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.content != nil, @"");
  pigeonResult.scene = [GetNullableObjectAtIndex(list, 2) integerValue];
  return pigeonResult;
}
+ (nullable QQShareBaseModel *)nullableFromList:(NSArray *)list {
  return (list) ? [QQShareBaseModel fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.title ?: [NSNull null]),
    (self.content ?: [NSNull null]),
    @(self.scene),
  ];
}
@end

@implementation QQSdkOnResp
+ (instancetype)makeWithType:(NSNumber *)type
    description:(nullable NSString *)description
    result:(nullable NSString *)result
    extendInfo:(nullable NSString *)extendInfo
    errorDescription:(nullable NSString *)errorDescription {
  QQSdkOnResp* pigeonResult = [[QQSdkOnResp alloc] init];
  pigeonResult.type = type;
  pigeonResult.description = description;
  pigeonResult.result = result;
  pigeonResult.extendInfo = extendInfo;
  pigeonResult.errorDescription = errorDescription;
  return pigeonResult;
}
+ (QQSdkOnResp *)fromList:(NSArray *)list {
  QQSdkOnResp *pigeonResult = [[QQSdkOnResp alloc] init];
  pigeonResult.type = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.type != nil, @"");
  pigeonResult.description = GetNullableObjectAtIndex(list, 1);
  pigeonResult.result = GetNullableObjectAtIndex(list, 2);
  pigeonResult.extendInfo = GetNullableObjectAtIndex(list, 3);
  pigeonResult.errorDescription = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable QQSdkOnResp *)nullableFromList:(NSArray *)list {
  return (list) ? [QQSdkOnResp fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.type ?: [NSNull null]),
    (self.description ?: [NSNull null]),
    (self.result ?: [NSNull null]),
    (self.extendInfo ?: [NSNull null]),
    (self.errorDescription ?: [NSNull null]),
  ];
}
@end

@implementation QQShareWebPage
+ (instancetype)makeWithPageUrl:(NSString *)pageUrl
    thumbImageUrl:(NSString *)thumbImageUrl
    base:(QQShareBaseModel *)base {
  QQShareWebPage* pigeonResult = [[QQShareWebPage alloc] init];
  pigeonResult.pageUrl = pageUrl;
  pigeonResult.thumbImageUrl = thumbImageUrl;
  pigeonResult.base = base;
  return pigeonResult;
}
+ (QQShareWebPage *)fromList:(NSArray *)list {
  QQShareWebPage *pigeonResult = [[QQShareWebPage alloc] init];
  pigeonResult.pageUrl = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.pageUrl != nil, @"");
  pigeonResult.thumbImageUrl = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.thumbImageUrl != nil, @"");
  pigeonResult.base = [QQShareBaseModel nullableFromList:(GetNullableObjectAtIndex(list, 2))];
  NSAssert(pigeonResult.base != nil, @"");
  return pigeonResult;
}
+ (nullable QQShareWebPage *)nullableFromList:(NSArray *)list {
  return (list) ? [QQShareWebPage fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.pageUrl ?: [NSNull null]),
    (self.thumbImageUrl ?: [NSNull null]),
    (self.base ? [self.base toList] : [NSNull null]),
  ];
}
@end

@implementation QQShareImage
+ (instancetype)makeWithImageData:(nullable FlutterStandardTypedData *)imageData
    base:(QQShareBaseModel *)base {
  QQShareImage* pigeonResult = [[QQShareImage alloc] init];
  pigeonResult.imageData = imageData;
  pigeonResult.base = base;
  return pigeonResult;
}
+ (QQShareImage *)fromList:(NSArray *)list {
  QQShareImage *pigeonResult = [[QQShareImage alloc] init];
  pigeonResult.imageData = GetNullableObjectAtIndex(list, 0);
  pigeonResult.base = [QQShareBaseModel nullableFromList:(GetNullableObjectAtIndex(list, 1))];
  NSAssert(pigeonResult.base != nil, @"");
  return pigeonResult;
}
+ (nullable QQShareImage *)nullableFromList:(NSArray *)list {
  return (list) ? [QQShareImage fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.imageData ?: [NSNull null]),
    (self.base ? [self.base toList] : [NSNull null]),
  ];
}
@end

@interface QQOpenSdkApiCodecReader : FlutterStandardReader
@end
@implementation QQOpenSdkApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [QQShareBaseModel fromList:[self readValue]];
    case 129: 
      return [QQShareImage fromList:[self readValue]];
    case 130: 
      return [QQShareWebPage fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface QQOpenSdkApiCodecWriter : FlutterStandardWriter
@end
@implementation QQOpenSdkApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[QQShareBaseModel class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[QQShareImage class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[QQShareWebPage class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface QQOpenSdkApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation QQOpenSdkApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[QQOpenSdkApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[QQOpenSdkApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *QQOpenSdkApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    QQOpenSdkApiCodecReaderWriter *readerWriter = [[QQOpenSdkApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void QQOpenSdkApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<QQOpenSdkApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.qq_opensdk_flutter.QQOpenSdkApi.registerApp"
        binaryMessenger:binaryMessenger
        codec:QQOpenSdkApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(registerAppAppId:urlSchema:universalLink:completion:)], @"QQOpenSdkApi api (%@) doesn't respond to @selector(registerAppAppId:urlSchema:universalLink:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_appId = GetNullableObjectAtIndex(args, 0);
        NSString *arg_urlSchema = GetNullableObjectAtIndex(args, 1);
        NSString *arg_universalLink = GetNullableObjectAtIndex(args, 2);
        [api registerAppAppId:arg_appId urlSchema:arg_urlSchema universalLink:arg_universalLink completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.qq_opensdk_flutter.QQOpenSdkApi.isQQInstalled"
        binaryMessenger:binaryMessenger
        codec:QQOpenSdkApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isQQInstalledWithCompletion:)], @"QQOpenSdkApi api (%@) doesn't respond to @selector(isQQInstalledWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api isQQInstalledWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.qq_opensdk_flutter.QQOpenSdkApi.joinQQGroup"
        binaryMessenger:binaryMessenger
        codec:QQOpenSdkApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(joinQQGroupQqGroupInfo:completion:)], @"QQOpenSdkApi api (%@) doesn't respond to @selector(joinQQGroupQqGroupInfo:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_qqGroupInfo = GetNullableObjectAtIndex(args, 0);
        [api joinQQGroupQqGroupInfo:arg_qqGroupInfo completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.qq_opensdk_flutter.QQOpenSdkApi.shareWebPage"
        binaryMessenger:binaryMessenger
        codec:QQOpenSdkApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(shareWebPageReq:completion:)], @"QQOpenSdkApi api (%@) doesn't respond to @selector(shareWebPageReq:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        QQShareWebPage *arg_req = GetNullableObjectAtIndex(args, 0);
        [api shareWebPageReq:arg_req completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.qq_opensdk_flutter.QQOpenSdkApi.shareImage"
        binaryMessenger:binaryMessenger
        codec:QQOpenSdkApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(shareImageReq:completion:)], @"QQOpenSdkApi api (%@) doesn't respond to @selector(shareImageReq:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        QQShareImage *arg_req = GetNullableObjectAtIndex(args, 0);
        [api shareImageReq:arg_req completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface QQSdkOnRespApiCodecReader : FlutterStandardReader
@end
@implementation QQSdkOnRespApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [QQSdkOnResp fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface QQSdkOnRespApiCodecWriter : FlutterStandardWriter
@end
@implementation QQSdkOnRespApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[QQSdkOnResp class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface QQSdkOnRespApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation QQSdkOnRespApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[QQSdkOnRespApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[QQSdkOnRespApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *QQSdkOnRespApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    QQSdkOnRespApiCodecReaderWriter *readerWriter = [[QQSdkOnRespApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

@interface QQSdkOnRespApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation QQSdkOnRespApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)onRespResp:(QQSdkOnResp *)arg_resp completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.qq_opensdk_flutter.QQSdkOnRespApi.onResp"
      binaryMessenger:self.binaryMessenger
      codec:QQSdkOnRespApiGetCodec()];
  [channel sendMessage:@[arg_resp ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
@end

