// Autogenerated from Pigeon (v11.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class QQSceneType(val raw: Int) {
  QQ(0),
  QZONE(1);

  companion object {
    fun ofRaw(raw: Int): QQSceneType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class QQShareRetCode(val raw: Int) {
  SUCCESS(0),
  FAILED(1),
  COMMON(2),
  USERCANCEL(3);

  companion object {
    fun ofRaw(raw: Int): QQShareRetCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class QQShareBaseModel (
  val title: String,
  val content: String,
  val thumbImageUrl: String,
  val scene: QQSceneType

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): QQShareBaseModel {
      val title = list[0] as String
      val content = list[1] as String
      val thumbImageUrl = list[2] as String
      val scene = QQSceneType.ofRaw(list[3] as Int)!!
      return QQShareBaseModel(title, content, thumbImageUrl, scene)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      title,
      content,
      thumbImageUrl,
      scene.raw,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class QQSdkOnResp (
  val type: Long,
  val description: String? = null,
  val result: String? = null,
  val extendInfo: String? = null,
  val errorDescription: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): QQSdkOnResp {
      val type = list[0].let { if (it is Int) it.toLong() else it as Long }
      val description = list[1] as String?
      val result = list[2] as String?
      val extendInfo = list[3] as String?
      val errorDescription = list[4] as String?
      return QQSdkOnResp(type, description, result, extendInfo, errorDescription)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      type,
      description,
      result,
      extendInfo,
      errorDescription,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class QQShareWebPage (
  val pageUrl: String,
  val base: QQShareBaseModel

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): QQShareWebPage {
      val pageUrl = list[0] as String
      val base = QQShareBaseModel.fromList(list[1] as List<Any?>)
      return QQShareWebPage(pageUrl, base)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      pageUrl,
      base.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class QQShareImage (
  val imageData: ByteArray? = null,
  val base: QQShareBaseModel

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): QQShareImage {
      val imageData = list[0] as ByteArray?
      val base = QQShareBaseModel.fromList(list[1] as List<Any?>)
      return QQShareImage(imageData, base)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      imageData,
      base.toList(),
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object QQOpenSdkApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          QQShareBaseModel.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          QQShareImage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          QQShareWebPage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is QQShareBaseModel -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is QQShareImage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is QQShareWebPage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface QQOpenSdkApi {
  fun registerApp(appId: String, urlSchema: String, universalLink: String?, callback: (Result<Unit>) -> Unit)
  fun isQQInstalled(callback: (Result<Boolean>) -> Unit)
  fun joinQQGroup(qqGroupInfo: String, callback: (Result<Boolean>) -> Unit)
  fun shareWebPage(req: QQShareWebPage, callback: (Result<Boolean>) -> Unit)
  fun shareImage(req: QQShareImage, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by QQOpenSdkApi. */
    val codec: MessageCodec<Any?> by lazy {
      QQOpenSdkApiCodec
    }
    /** Sets up an instance of `QQOpenSdkApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: QQOpenSdkApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.qq_opensdk_flutter.QQOpenSdkApi.registerApp", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appIdArg = args[0] as String
            val urlSchemaArg = args[1] as String
            val universalLinkArg = args[2] as String?
            api.registerApp(appIdArg, urlSchemaArg, universalLinkArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.qq_opensdk_flutter.QQOpenSdkApi.isQQInstalled", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isQQInstalled() { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.qq_opensdk_flutter.QQOpenSdkApi.joinQQGroup", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val qqGroupInfoArg = args[0] as String
            api.joinQQGroup(qqGroupInfoArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.qq_opensdk_flutter.QQOpenSdkApi.shareWebPage", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reqArg = args[0] as QQShareWebPage
            api.shareWebPage(reqArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.qq_opensdk_flutter.QQOpenSdkApi.shareImage", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reqArg = args[0] as QQShareImage
            api.shareImage(reqArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object QQSdkOnRespApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          QQSdkOnResp.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is QQSdkOnResp -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
class QQSdkOnRespApi(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by QQSdkOnRespApi. */
    val codec: MessageCodec<Any?> by lazy {
      QQSdkOnRespApiCodec
    }
  }
  fun onResp(respArg: QQSdkOnResp, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.qq_opensdk_flutter.QQSdkOnRespApi.onResp", codec)
    channel.send(listOf(respArg)) {
      callback()
    }
  }
}
